# Generated by Django 5.1.4 on 2025-03-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_task_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="Название специализации"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание специализации"
                    ),
                ),
            ],
            options={
                "verbose_name": "Специализация",
                "verbose_name_plural": "Специализации",
                "ordering": ("name",),
            },
        ),
        migrations.RemoveField(
            model_name="employee",
            name="position",
        ),
        migrations.AddField(
            model_name="employee",
            name="positions",
            field=models.ManyToManyField(
                help_text="Выберите одну или несколько специализаций сотрудника",
                related_name="employees",
                to="tracker.position",
                verbose_name="Специализации",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="required_positions",
            field=models.ManyToManyField(
                help_text="Выберите необходимые специализации для выполнения задачи",
                related_name="tasks",
                to="tracker.position",
                verbose_name="Требуемые специализации",
            ),
        ),
    ]
