# Generated by Django 5.1.4 on 2025-01-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новая"),
                    ("in_progress", "В работе"),
                    ("on_review", "На проверке"),
                    ("completed", "Завершена"),
                    ("canceled", "Отменена"),
                ],
                default="new",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
